timezone: Asia/Shanghai

i18n:
  domain: default
  locale:
#   query: lng
#   cookie: hail_lng
    default: zh_CN
  alias:
    zh: zh_CN

allow_origin: http://127.0.0.1:3000

output:
  Api: json
  Panel: template