# Feature
config: Hail\Config

alias:
  class|to: Hail\AliasLoader
  arguments: [CONFIG.alias]

i18n: Hail\I18N\I18N

event:
  class|to: Hail\Event\EventManager
  to:
    - Psr\EventManager\EventManagerInterface

acl: Hail\Acl

browser: Hail\Browser

cache: "@cache.simple"

cache.simple:
  factory: Hail\Factory\Cache::simple
  to:
    - Hail\Cache\Simple\CacheInterface
    - Psr\SimpleCache\CacheInterface

cache.pool:
  factory: Hail\Factory\Cache::pool
  to:
    - Hail\Cache\CacheItemPoolInterface
    - Psr\Cache\CacheItemPoolInterface

cookie:
  class|to: Hail\Cookie
  arguments: [CONFIG.cookie]

db: Hail\Factory\Database::pdo

cdb: Hail\Database\Cache

output: Hail\Output

router:
  class|to: Hail\Router
  arguments: [CONFIG.route]

session:
  class|to: Hail\Session
  arguments: [CONFIG.session, CONFIG.cookie]

storage: Hail\Factory\Storage::mount

template:
  class|to: Hail\Latte\Engine
  arguments: [CONFIG.template]

# Tools
arrays: Hail\Util\Arrays
crypto: Hail\Util\Crypto
debugger: Hail\Tracy\Debugger
logger:
  factory: Hail\Tracy\Debugger::getLogger
  to:
    - Psr\Log\LoggerInterface
generators: Hail\Util\Generators
inflector: Hail\Util\Inflector
json: Hail\Util\Json
serialize: Hail\Util\Serialize
strings: Hail\Util\Strings
validator: Hail\Util\Validator

# Application
app:
  class|to: Hail\Application
  arguments: ["@container"]

request: Hail\Http\Request

response:
  class|to: Hail\Http\Response
  arguments: ["@app", "@request"]

lib:
  class: Hail\Util\ObjectFactory
  arguments: [App\Library, "@container"]

model:
  class: Hail\Util\ObjectFactory
  arguments: [App\Model, "@container"]

# Middleware
Hail\Http\Middleware\ErrorHandler: []
Hail\Http\Middleware\MethodOverride: []
Hail\Http\Middleware\BasePath:
  arguments: [CONFIG.app.basePath]
Hail\Http\Middleware\ClientIp:
  calls:
    proxy: [CONFIG.env.proxies]
Hail\Http\Middleware\Cors:
  arguments: [CONFIG.cors]
Hail\Http\Middleware\Payload: []
Hail\Http\Middleware\ScriptPath: []
Hail\Http\Middleware\TrailingSlash: []
Hail\Http\Middleware\ContentType: []
Hail\Http\Middleware\ContentEncoding: []
Hail\Http\Middleware\ContentLanguage:
  arguments: [CONFIG.env.languages]

# Hail Framework middleware
Hail\Http\Middleware\I18n:
  arguments: ["@container"]
Hail\Http\Middleware\Route:
  arguments: ["@app"]
